name    'jhoblitt-mcelog'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-mcelog'
source 'https://github.com/jhoblitt/puppet-mcelog.git'
summary 'Manages the `mcelog` utility for x86-64 CPU Machine Check Exception data'
description 'Manages the `mcelog` utility for x86-64 CPU Machine Check Exception data'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
